//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviseAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class J_Vibit
    {
        public int ID_Pokup { get; set; }
        public int ID_Naklad_Prodag { get; set; }
        public int ID_Sotrudnic { get; set; }
        public System.DateTime Data_Vibitia { get; set; }
        public string Nomer { get; set; }
        public decimal Summa { get; set; }
        public decimal Dostavka { get; set; }
        public decimal Summa_Obh { get; set; }
    
        public virtual Pokup Pokup { get; set; }
        public virtual Sotrudnic Sotrudnic { get; set; }
    }
}
