//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviseAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nakladna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nakladna()
        {
            this.Sost_Nakladna = new HashSet<Sost_Nakladna>();
        }
    
        public int ID_Nakladna { get; set; }
        public int ID_Postavhick { get; set; }
        public int ID_Sotrudnic { get; set; }
        public System.DateTime Data_Postavki { get; set; }
        public string Nomer { get; set; }
    
        public virtual Postavhick Postavhick { get; set; }
        public virtual Sotrudnic Sotrudnic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sost_Nakladna> Sost_Nakladna { get; set; }
    }
}
