//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviseAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sklad
    {
        public int ID_Sklad { get; set; }
        public int ID_Tovar { get; set; }
        public int ID_PodTip { get; set; }
        public int ID_Tip { get; set; }
        public string Tip { get; set; }
        public string PodTip { get; set; }
        public string Tovar { get; set; }
        public string Opisanie { get; set; }
        public int Koll { get; set; }
        public Nullable<int> Sredn_Zena { get; set; }
        public byte[] Image { get; set; }
    }
}
