//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviseAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Nakladna
    {
        public int ID_Nakladna { get; set; }
        public int ID_Postavhick { get; set; }
        public int ID_Sotrudnic { get; set; }
        public string Naimenovanie_Organiz { get; set; }
        public string Telefon { get; set; }
        public string FIO_Sotrudnic { get; set; }
        public System.DateTime Data_Postavki { get; set; }
        public string Nomer { get; set; }
    }
}
