//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviseAPI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sotrudnic
    {
        public int ID_Sotrudnic { get; set; }
        public string FIO { get; set; }
        public string Telefon { get; set; }
        public string Familia { get; set; }
        public string Imia { get; set; }
        public string Otzh { get; set; }
    }
}
